config/routes.rb
Account::Application.routes.draw do

  resources :productions,:except=>[:destroy] do
    member do
      get :approved
    end
  end

  resources :summaries,:only=>[:index,:edit,:update]

  resources :bill_return_vouchers,:except=>[:destroy]

  resources :invoice_return_vouchers,:except=>[:destroy]

  resources :balance_sheets,:except=>[:destroy]

  resources :profit_and_losses,:except=>[:destroy]

  resources :general_ledgers,:except=>[:destroy]

  resources :trial_balances,:except=>[:destroy]
  resources :general_receipt_vouchers,:except=>[:destroy,:show]

  resources :invoice_receipt_vouchers,:except=>[:destroy,:index,:show]

  resources :general_payment_vouchers,:except=>[:destroy,:show]

  resources :bill_payment_vouchers,:except=>[:destroy,:index,:show]

  resources :journal_vouchers,:except=>[:destroy,:show] 

  resources :bills,:except=>[:destroy] do
  member do
    get :transaction
  end
  end

  resources :invoice_items,:except=>[:destroy]

  resources :invoices,:except=>[:destroy] do
    member do
      get :transaction
    end
  end
  resources :return_invoices,:except=>[:index,:destroy] do
  member do
    get :transaction
  end
  end
  resources :customers,:except=>[:destroy]

  resources :suppliers,:except=>[:destroy]

  resources :tax_codes,:except=>[:show,:destroy]

  resources :items,:except=>[:show,:destroy]

  resources :accounts,:except=>[:destroy]

  get "find_customer/:id" => "customers#find_customer"
  get "find_supplier/:id" => "suppliers#find_supplier"
  get 'payment' => "payment_vouchers#index"
  get 'report'  => "reports#index"
  get "settings" =>"settings#index"
  get "inventory" =>"inventory#index"
  root 'summaries#index'

  

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :customer
  has_many :invoice_items,:dependent=>:destroy
  has_many :invoice_receipts,:dependent=>:destroy
  has_many :transactions, :as => :commercial_document,:class_name => "Plutus::Transaction"
  has_many :inventory_outs, :as => :commercial_document
  has_many :return_invoices, :dependent=>:destroy
  before_save :validate_fields
  validates_presence_of :issue_date,:customer_id
  validates_uniqueness_of :invoice_no
  validate :item_quantity?
  accepts_nested_attributes_for :invoice_items, :reject_if => lambda { |a| a[:item_id].blank? or a[:account_id].blank? or a[:price].blank? }, :allow_destroy => true
  protected

   def validate_fields
     self.amount = 0 if self.amount.blank?
   end
   def self.debits(invoice)
    Plutus::Account
    @debit_account = Plutus::Asset.find_or_create_by(:name => "Account receivable")
    [{:account=>Plutus::Account.find(@debit_account.id),:amount=>(invoice.amount.round(2))}]
   end
   def self.credits(invoice)
    Plutus::Account
    credits = []
    invoice.invoice_items.each do |invoice_item|
      if invoice_item.tax_code.blank?
        credits << {:account=>Plutus::Account.find(invoice_item.account_id),:amount=>invoice_item.amount.round(2)}
      else
         @tax_account = Plutus::Liability.find_or_create_by(:name => invoice_item.tax_code.name)
        credits << {:account=>Plutus::Account.find(invoice_item.account_id),:amount=>(invoice_item.amount - invoice_item.tax_amount.round(2)).round(2)}
        credits << {:account=>Plutus::Account.find(@tax_account.id),:amount=>invoice_item.tax_amount.round(2)}
      end
    end
    credits
   end
    def self.make_transaction(invoice)
       transaction = Plutus::Transaction.build(:transaction_date => invoice.issue_date,:description => "Being Invoice Created", :commercial_document => invoice,
       :debits=>self.debits(invoice),:credits=>self.credits(invoice))
      transaction
    end
    def item_quantity?
      self.invoice_items.each do |invoice_item|
      item = Item.find(invoice_item.item.id)
      errors[:base] << "Item Quantity must be less then stock" if item.inventory_ins.sum(:in_stock) < invoice_item.qty
      end
    end 
    def self.search(search)
      if search
        begin
          where('issue_date = ?', search.to_date)
        rescue
          where('invoice_no LIKE ?',"%#{search}%")
        end
      else
        all.order('issue_date DESC')
      end
  end 
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.search(params[:search]).order("issue_date Desc").paginate(:page => params[:page], :per_page => 30 )
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    1.times do
      invoice_items = @invoice.invoice_items.build
    end
  end

  # GET /invoices/1/edit
  def edit
    if @invoice.transactions.count >0
      redirect_to @invoice,notice: 'Invoice is locked'
    end
  end
 def create
    @invoice = Invoice.new(invoice_params)
     respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice}
        format.json { render action: 'show', status: :created, location: @invoice }
      else
        format.html { render action: 'new' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update_attributes(invoice_params) 
        format.html { redirect_to @invoice}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def transaction
    Invoice.transaction do
    @invoice = Invoice.find(params[:id])
        @transaction = Invoice.make_transaction(@invoice)
          @invoice.invoice_items.each do |invoice_item|
          item = Item.find(invoice_item.item.id)
          issue_quantity = invoice_item.qty
          item.inventory_ins.where("in_stock > 0").order("in_date").each do |inventory_item|
            unless issue_quantity.to_f <= 0
              if inventory_item.in_stock.to_f > issue_quantity
                inventory_out = InventoryOut.new(:item_id=>item.id,:quantity=>issue_quantity.to_f,:rate=>inventory_item.rate,:amount=>(issue_quantity.to_f*inventory_item.rate.to_f),:out_date=>@invoice.issue_date,:commercial_document => @invoice)
                inventory_out.save
                inventory_item.update(:in_stock=>inventory_item.in_stock.to_f-issue_quantity.to_f)
                issue_quantity = 0.0
              else
                inventory_out = InventoryOut.new(:item_id=>item.id,:quantity=>inventory_item.in_stock,:rate=>inventory_item.rate,:amount=>(inventory_item.in_stock.to_f*inventory_item.rate.to_f),:out_date=>@invoice.issue_date,:commercial_document => @invoice)
                inventory_out.save
                issue_quantity = issue_quantity - inventory_item.in_stock
                inventory_item.update(:in_stock=>0.0)
              end
            end
          end
        end
        raise ActiveRecord::Rollback unless @transaction.save
      end
     redirect_to @invoice
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:invoice_no, :issue_date, :due_date, :customer_id, :internal_information, :amount, :amount_received,:invoice_items_attributes=>[:id,:item_id,:account_id,:qty,:price,:tax_code_id, :tax_amount,:amount,:_destroy])
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
	def balance_due(invoice)
      balance_due = invoice.amount.to_f
      if invoice.return_invoices.nil?
      	balance_due = balance_due
      else
      	balance_due = balance_due - invoice.return_invoices.sum('amount')
      end
      balance_due -= invoice.amount_received.to_f

      return balance_due
	end
	def invoice_balance_due(invoice)
      balance_due = invoice.amount.to_f
      invoice.return_invoices.each do |return_invoice|
        if return_invoice.transactions.count > 0
        	balance_due -= return_invoice.amount.to_f
        else
        	balance_due = balance_due
        end
      end 
        balance_due -= invoice.amount_received.to_f
        return balance_due 
	end	

  def return_invoices(return_invoices)
   return_amount = BigDecimal.new('0')
   return_invoices.each do |return_invoice|
   return_amount += Plutus::CreditAmount.where('transaction_id IN(?)',return_invoice.transactions).sum('amount')
   end
   return return_amount
  end
end

app/views/invoices/_form.html.haml
= form_for @invoice do |f|
  - if @invoice.errors.any?
    #error_explanation
      %h2= "#{pluralize(@invoice.errors.count, "error")} prohibited this invoice from being saved:"
      %ul
        - @invoice.errors.full_messages.each do |msg|
          %li= msg
  .row
    .field.col-xs-6
      = f.label :invoice_no
      = f.text_field :invoice_no,:class=>"form-control"
  .row
    .field.col-xs-3
      = f.label :issue_date
      = f.text_field :issue_date,'data-behaviour' => 'datepicker',value: "#{Date.today.strftime('%d-%m-%Y')}",:class=>"form-control"
    .field.col-xs-3
      = f.label :due_date
      = f.text_field :due_date,'data-behaviour' => 'datepicker',value: if f.object.due_date.nil? then "#{Date.today.strftime('%d-%m-%Y')}" else f.object.due_date.strftime('%d-%m-%Y') end,:class=>"form-control"
  .row
    .field.col-xs-6
      = f.label :customer
      = f.select :customer_id,Customer.all.order(:name).map{|p|[p.name,p.id]},{:include_blank =>'Select A Customer',:selected => f.object.customer_id},:class=>'chzn-select form-control',onchange: 'find_customer(this)'
  .row  
    .field.col-xs-6
      = label_tag :billing_address
      = text_area_tag :billing_address,if f.object.customer.nil? then '' else f.object.customer.address  end,:class=>"form-control"
  .field
  .field{:style=>'display:inline-block;'}
    =f.label :invoice_item
  .field{:style=>'display:inline-block;padding-left:100px;'}
    =f.label :account
  .field{:style=>'display:inline-block;padding-left:120px;'}
    =f.label :qty
  .field{:style=>'display:inline-block;padding-left:35px;'}
    =f.label :price
  .field{:style=>'display:inline-block;padding-left:35px;'}
    =f.label :amount
  .field{:style=>'display:inline-block;padding-left:35px;'}
    =f.label "Tax(included)"    
  .field
    = f.fields_for :invoice_items do |items|
      = render "invoice_items_fields", :f => items
    %p= link_to_add_fields "Add more", f,:invoice_items
  .field{:style=>'margin-left:465px;'}
    = f.text_field :amount,:placeholder=>'0.0',:value=>f.object.amount,:style=>'width:80px;',:id=>"invoive_amount",:class=>"form-control"
  .field
    = f.label :internal_information
    = f.text_area :internal_information,:class=>"form-control"
  %br
  .actions
    = f.submit 'Create',:class=>'btn btn-primary'
    = link_to 'Back', invoices_path,:class=>'btn btn-default'

app/views/invoices/_invoice_items_fields.html.haml
.fields
  .field{:style=>'display:inline-block;'}
    = f.select :item_id,Item.joins(:inventory_ins).where("inventory_ins.in_stock > 0").order(:name).uniq.map{|p|[p.name,p.id]},{:include_blank =>'Select Item',:selected => f.object.item_id},:class=>'chzn-select',:style=>'width:160px;'
  .field{:style=>'display:inline-block;'}
    = f.select :account_id,Plutus::Account.all.order(:type).map{|p|[p.name,p.id]},{:include_blank =>'Select Account',:selected => f.object.account_id},:class=>'chzn-select',:style=>'width:180px;'
  .field{:style=>'display:inline-block;'}
    = f.text_field :qty,:placeholder=>'1',:id=>'invoice_invoice_items__qty',:style=>'width:50px;'
  .field{:style=>'display:inline-block;'}
    = f.text_field :price,:placeholder=>'0.0',onkeyup: "total_amount(this)",:style=>'width:60px;'
  .field{:style=>'display:inline-block;'}
    = f.text_field :amount,:placeholder=>'0.0',:value=>f.object.amount,:class=>'amount_field',:readonly=>true,:id=>'invoice_invoice_items__amount'
  .field{:style=>'display:inline-block;'}
    = f.select :tax_code_id,TaxCode.all.order(:name).map{|p|[p.name.to_s+" #{p.rate}%",p.id]},{:include_blank =>'Tax code'},:class=>'chzn-select',:style=>'width:120px;'
    = f.hidden_field :tax_amount,:value=>'0.0'
  .field{:style=>'display:inline-block;'} 
    = link_to_remove_invoice_fields "Remove", f
%script
  $('.chzn-select').chosen()

app/views/invoices/edit.html.haml
.row
  .col-md-12.content-wrapper
    %h3 Editing Invoice
    %hr
    = render 'form'

app/views/invoices/index.html.haml
.row
  .pull-right
    = form_for invoices_path,:method=>'GET',:html=>{:class=>'navbar-form navbar-left'} do
      = text_field_tag :search,params[:search],:placeholder=>'Search...',:style=>'width:290px;',:class=>"form-control"
.row
  .col-md-12.content-wrapper 
    .row
      .col-md-12
        %table.table.table-condensed.table-striped.table-bordered.table-responsive
          %tr
            %th{:colspan=>9}
              %h4{:style=>"display:inline; padding-right: 20px; line-height: 1.5em"}
                Invoices
              = link_to 'New Invoice', new_invoice_path,:class=>"btn btn-default pull-right"
          %tr.table-header-row.table-striped
            %th
              %i.icon-edit
            %th
              %i.icon-eye-open
            %th IssueDate
            %th #
            %th Customer
            %th.amount Amount 
            %th.amount Balance Due
            %th DueDate
          - @invoices.each do |invoice|
            %tr
              - if invoice.transactions.count > 0
                %td=image_tag "lock.jpeg",:height=>'20px',:width=>'30px',:class=>'btn btn-default btn-xs'
              -else
                %td= link_to 'Edit', edit_invoice_path(invoice),:class=>"btn btn-default btn-xs active"            
              %td= link_to 'View', invoice,:class=>"btn btn-default btn-xs active"
              %td= invoice.issue_date.strftime('%d/%m/%Y') if !invoice.issue_date.nil?
              %td= invoice.invoice_no if !invoice.invoice_no.nil?
              %td= invoice.customer.name if !invoice.customer.nil?
              %th.amount= number_to_currency(invoice.amount,unit:'') if !invoice.amount.nil?
              %th.amount= number_to_currency(invoice.amount.to_f - invoice.amount_received.to_f,unit:'') if !invoice.amount.nil?
              %td= invoice.due_date.strftime('%d/%m/%Y')  if !invoice.due_date.nil? 
  = will_paginate @invoices,:renderer => BootstrapPagination::Rails                       

app/views/invoices/new.html.haml
.row
  .col-md-12.content-wrapper
    %h3 Create Invoice
    %hr
    = render 'form'

app/views/invoices/show.html.haml
.row
  .col-md-12.content-wrapper
    .row
      .col-md-12
        .col-md-3.pull-right
          = image_tag 'prosrc.png'   
        .col-md-6
          %h2 Tax Invoice
          %br
          %br
    .row
      .col-md-6
        %p
          %b To:
          = @invoice.customer.name
        %p
          %b 
          = @invoice.customer.address
      .col-md-4.pull-right
        %p
          %b Date:
          = @invoice.issue_date.strftime('%d/%m/%Y')
        %p
          %b Invoice No:
          = @invoice.invoice_no
    %br
    %table.table.table-bordered.table-responsive
      %tr.table-header-row.table-striped
        %th Item & Specification
        %th.amount Qty
        %th.amount Price
        %th.amount Amount

      - @invoice.invoice_items.each do |invoice_item|
        %tr
          %td.borderless= invoice_item.item.name
          %td.amount= invoice_item.qty
          %td.amount= number_to_currency(invoice_item.price.round(2), unit:'')
          %td.amount= number_to_currency(invoice_item.amount.round(2),unit:'')
      %tr
        %th.borderless.amount{:colspan=>3}Total
        %th.amount= number_to_currency(@invoice.amount,unit:'')
      - @invoice.invoice_items.group('tax_code_id').select('SUM(tax_amount) as tax_amount,tax_code_id').each do |tax|
        -if !tax.tax_code.blank?
          %tr
            %td.borderless.amount{:colspan=>3}=tax.tax_code.name+"  #{tax.tax_code.rate}%"+" "+"(Included)"
            %td.amount= number_to_currency(tax.tax_amount,unit:'')
      %tr
        %td.borderless.amount{:colspan=>3}Amount Received
        %td.amount= if @invoice.amount_received.blank? then '0.00' else number_to_currency(@invoice.amount_received,unit:'') end
      -if @invoice.return_invoices.joins(:transactions).count > 0
        %tr
          %td.borderless.amount{:colspan=>3}Return
          %td.amount= if @invoice.return_invoices.sum('amount').blank? then '0.00' else number_to_currency(return_invoices(@invoice.return_invoices),unit:'') end
      %tr
        %th.amount{:colspan=>3}Balance Due
        %th.amount= number_to_currency(invoice_balance_due(@invoice),unit:'')
    .col-md-12
      %p
        %b **Additional Note:
        =@invoice.internal_information
%br
-if @invoice.transactions.count >0
  %ul.nav.nav-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#irc"} Invoice Receipts
    %li
      %a{"data-toggle" => "tab", href: "#irn"} Invoice Return
  .tab-content
    #irc.tab-pane.active    
      %table.table.table-condensed.table-striped.table-bordered.table-responsive
        %tr
          %th{:colspan=>6}
            %h4{:style=>"display:inline; padding-right: 20px; line-height: 1.5em"}
              Invoices Receipts
            = link_to 'Receive money from customer', new_invoice_receipt_voucher_path(:invoice_id=>@invoice.id),:class=>'btn btn-primary pull-right'
        %tr.table-header-row.table-striped
          %th
            %i.icon-edit
          %th #
          %th Date
          %th Description
          %th Payment From
          %th.amount Amount
        -if @invoice.invoice_receipts.count >0
          - @invoice.invoice_receipts.each do |invoice_receipt|
            %tr.table-header-row.table-striped
              %td=link_to 'Edit', edit_invoice_receipt_voucher_path(invoice_receipt,:invoice_id=>@invoice),:class=>"btn btn-default btn-xs active"
              %th= invoice_receipt.invoice_receipt_voucher.reference_no
              %td= invoice_receipt.invoice_receipt_voucher.payment_date
              %td= invoice_receipt.invoice_receipt_voucher.description
              %td= invoice_receipt.invoice_receipt_voucher.account.name
              %td.amount= number_to_currency(invoice_receipt.amount.round(2),unit:'')
        - else
          %tr
            %th{:colspan=>6} No Payment received Customer for this Invoice
    #irn.tab-pane      
      %table.table.table-condensed.table-striped.table-bordered.table-responsive
        %tr
          %th{:colspan=>6}
            %h4{:style=>"display:inline; padding-right: 20px; line-height: 1.5em"}
              Invoices Return
            = link_to 'Return this invoice', new_return_invoice_path(:invoice_id=>@invoice.id),:class=>'btn btn-primary pull-right'
        %tr.table-header-row.table-striped
          %th
            %i.icon-edit
          %th
            %i.icon-eye-open
          %th #
          %th Date
          %th Description
          %th.amount Amount
        -if @invoice.return_invoices.count >0
          - @invoice.return_invoices.each do |return_invoice|
            %tr
              - if return_invoice.transactions.count > 0
                %td=image_tag "lock.jpeg",:height=>'20px',:width=>'30px',:class=>'btn btn-default btn-xs' 
              -else   
                %td=link_to 'Edit', edit_return_invoice_path(return_invoice,:invoice_id=>return_invoice.invoice.id),:class=>'btn btn-default btn-xs'
              %th=link_to 'View', return_invoice,:class=>"btn btn-default btn-xs active"  
              %th=return_invoice.reference_no
              %td=return_invoice.return_date.strftime('%d/%m/%Y')
              %td=return_invoice.description
              %td.amount=number_to_currency(return_invoice.amount.round(2),unit:'')
        - else
          %tr
            %th{:colspan=>6} No Return transactions for this Invoice 

%br
  -if @invoice.transactions.count <=0
    = link_to 'Edit this invoice', edit_invoice_path(@invoice),:class=>'btn btn-default' 
    = link_to 'Save this invoice', transaction_invoice_path(@invoice),:class=>'btn btn-primary',data: { disable_with: "Please wait..." } 