config/routes.rb
Account::Application.routes.draw do

  resources :productions,:except=>[:destroy] do
    member do
      get :approved
    end
  end

  resources :summaries,:only=>[:index,:edit,:update]

  resources :bill_return_vouchers,:except=>[:destroy]

  resources :invoice_return_vouchers,:except=>[:destroy]

  resources :balance_sheets,:except=>[:destroy]

  resources :profit_and_losses,:except=>[:destroy]

  resources :general_ledgers,:except=>[:destroy]

  resources :trial_balances,:except=>[:destroy]
  resources :general_receipt_vouchers,:except=>[:destroy,:show]

  resources :invoice_receipt_vouchers,:except=>[:destroy,:index,:show]

  resources :general_payment_vouchers,:except=>[:destroy,:show]

  resources :bill_payment_vouchers,:except=>[:destroy,:index,:show]

  resources :journal_vouchers,:except=>[:destroy,:show] 

  resources :bills,:except=>[:destroy] do
  member do
    get :transaction
  end
  end

  resources :invoice_items,:except=>[:destroy]

  resources :invoices,:except=>[:destroy] do
    member do
      get :transaction
    end
  end
  resources :return_invoices,:except=>[:index,:destroy] do
  member do
    get :transaction
  end
  end
  resources :customers,:except=>[:destroy]

  resources :suppliers,:except=>[:destroy]

  resources :tax_codes,:except=>[:show,:destroy]

  resources :items,:except=>[:show,:destroy]

  resources :accounts,:except=>[:destroy]

  get "find_customer/:id" => "customers#find_customer"
  get "find_supplier/:id" => "suppliers#find_supplier"
  get 'payment' => "payment_vouchers#index"
  get 'report'  => "reports#index"
  get "settings" =>"settings#index"
  get "inventory" =>"inventory#index"
  root 'summaries#index'

  

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :supplier
  has_many :bill_items,:dependent=>:destroy
  has_many :bill_payments,:dependent=>:destroy
  has_many :transactions, :as => :commercial_document,:class_name => "Plutus::Transaction"
  has_many :inventory_ins, :as => :commercial_document
  before_save :validate_fields
  validates_presence_of :issue_date,:supplier_id
  validates_uniqueness_of :reference_no
  accepts_nested_attributes_for :bill_items, :reject_if => lambda { |a| a[:item_id].blank? or a[:account_id].blank? or a[:price].blank? }, :allow_destroy => true
 protected

   def validate_fields
     self.amount = 0 if self.amount.blank?
   end
   def self.debits(bill)
    Plutus::Account
    debits = []
    bill.bill_items.each do |bill_item|
      if bill_item.tax_code.blank?
        debits << {:account=>bill_item.account_id,:amount=>bill_item.amount.round(2)}
      else
        @tax_account = Plutus::Liability.find_or_create_by(:name => bill_item.tax_code.name)
        debits << {:account=>bill_item.account_id,:amount=>(bill_item.amount - bill_item.tax_amount.round(2)).round(2)}
        debits << {:account=>@tax_account.id,:amount=>bill_item.tax_amount.round(2)}
      end
    end
    debits
   end
   def self.credits(bill)
    Plutus::Account
    @credit_account = Plutus::Liability.find_or_create_by(:name => "Account Payable")
    [{:account=>@credit_account.id,:amount=>bill.amount.round(2)}]
   end
    def self.make_transaction(bill)
       transaction = Plutus::Transaction.build(:transaction_date => bill.issue_date,:description => "Being Bill Created", :commercial_document => bill,
       :debits=>self.debits(bill),:credits=>self.credits(bill))
      transaction
    end
  
  def self.search(search)
    if search
      begin
        where('issue_date = ?', search.to_date)
      rescue
        where('reference_no LIKE ?',"%#{search}%")
      end
    else
      all.order('issue_date DESC')
    end
  end


end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 30 )
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
    1.times do
      bill_items = @bill.bill_items.build
    end
  end

  # GET /bills/1/edit
  def edit
    if @bill.transactions.count >0
      redirect_to @bill,notice: 'Bill is locked'
    end
  end
  def create
    @bill = Bill.new(bill_params)
    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill}
        format.json { render action: 'show', status: :created, location: @bill }
      else
        format.html { render action: 'new' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update_attributes(bill_params) 
        format.html { redirect_to @bill}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  def transaction
    @bill = Bill.find(params[:id])
      @transaction = Bill.make_transaction(@bill)
      if @transaction.save
        @bill.bill_items.each do |bill_item|
          item = Item.find(bill_item.item.id)
          rate = if bill_item.tax_code.nil? then bill_item.price else bill_item.price-((bill_item.price*bill_item.tax_code.rate)/(100+bill_item.tax_code.rate)) end
          inventory = InventoryIn.new(:item_id=>item.id,:quantity=>bill_item.qty,:rate=>rate,:amount=>(bill_item.qty.to_f*rate.to_f),:in_stock=>bill_item.qty,:in_date=>@bill.issue_date,:commercial_document => @bill)
          inventory.save
        end
        redirect_to @bill
      else
        redirect_to @bill,notice: "#{@transaction.errors.first}"
      end  
  end
  private

  def sort_column
    Bill.column_names.include?(params[:sort]) ? params[:sort] : "issue_date"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:issue_date, :due_date, :supplier_id, :reference_no, :internal_information, :amount, :amount_paid,:bill_items_attributes=>[:id,:account_id,:item_id,:qty,:price,:tax_code_id, :tax_amount,:amount,:_destroy])
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_bill_accounts_fields.html.haml
.fields
  .row
    .field.col-xs-12
      .field{:style=>'display:inline-block;'}
        = f.select :item_id,Item.all.order(:name).map{|p|[p.name,p.id]},{:include_blank =>'Select A Item',:selected => f.object.item_id},:class=>'chzn-select',:style=>'width:160px;'
      .field{:style=>'display:inline-block;'}
        = f.select :account_id,Plutus::Account.all.order(:type).map{|p|[p.name,p.id]},{:include_blank =>'Select A Account',:selected => f.object.account_id},:class=>'chzn-select',:style=>'width:180px;'
      .field{:style=>'display:inline-block;'}
        = f.text_field :qty,:placeholder=>'1',:style=>'width:50px;',:id=>'bill_bill_accounts__qty'
      .field{:style=>'display:inline-block;'}
        = f.text_field :price,:placeholder=>'0.0',:style=>'width:60px;',onkeyup: "total_bill_amount(this)"
      .field{:style=>'display:inline-block;'}
        = f.text_field :amount,:placeholder=>'0.0',:value=>f.object.amount,:class=>'amount_field',:id=>'bill_bill_accounts_amount',:readonly=>true
      .field{:style=>'display:inline-block;'}
        = f.select :tax_code_id,TaxCode.all.order(:name).map{|p|[p.name.to_s+" #{p.rate}%",p.id]},{:include_blank =>'Tax code'},:class=>'chzn-select',:style=>'width:120px;',:id=>'bill_tax_code'
        = f.hidden_field :tax_amount, :value=>'0.0'
      .field{:style=>'display:inline-block;'}
      = link_to_remove_bill_fields "Remove", f
%script
  $('.chzn-select').chosen()

app/views/bills/_bill_items_fields.html.haml
.fields
  .row
    .field.col-xs-12
      .field{:style=>'display:inline-block;'}
        = f.select :item_id,Item.all.order(:name).map{|p|[p.name,p.id]},{:include_blank =>'Select A Item',:selected => f.object.item_id},:class=>'chzn-select',:style=>'width:160px;'
      .field{:style=>'display:inline-block;'}
        = f.select :account_id,Plutus::Account.all.order(:type).map{|p|[p.name,p.id]},{:include_blank =>'Select A Account',:selected => f.object.account_id},:class=>'chzn-select',:style=>'width:180px;'
      .field{:style=>'display:inline-block;'}
        = f.text_field :qty,:placeholder=>'1',:style=>'width:50px;',:id=>'bill_bill_accounts__qty'
      .field{:style=>'display:inline-block;'}
        = f.text_field :price,:placeholder=>'0.0',:style=>'width:60px;',onkeyup: "total_bill_amount(this)"
      .field{:style=>'display:inline-block;'}
        = f.text_field :amount,:placeholder=>'0.0',:value=>f.object.amount,:class=>'amount_field',:id=>'bill_bill_accounts_amount',:readonly=>true
      .field{:style=>'display:inline-block;'}
        = f.select :tax_code_id,TaxCode.all.order(:name).map{|p|[p.name.to_s+" #{p.rate}%",p.id]},{:include_blank =>'Tax code'},:class=>'chzn-select',:style=>'width:120px;',:id=>'bill_tax_code'
        = f.hidden_field :tax_amount, :value=>'0.0'
      .field{:style=>'display:inline-block;'}
      = link_to_remove_bill_fields "Remove", f
%script
  $('.chzn-select').chosen()

app/views/bills/_form.html.haml
= form_for @bill do |f|
  - if @bill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bill.errors.count, "error")} prohibited this bill from being saved:"
      %ul
        - @bill.errors.full_messages.each do |msg|
          %li= msg
  .row
    .field.col-xs-6
      = f.label :reference_no
      = f.text_field :reference_no,:class=>"form-control"
  .row
    .field.col-xs-3
      = f.label :issue_date
      = f.text_field :issue_date,'data-behaviour' => 'datepicker',value: "#{Date.today.strftime('%d-%m-%Y')}",:class=>"form-control"
    .field.col-xs-3
      = f.label :due_date
      = f.text_field :due_date,'data-behaviour' => 'datepicker',value: "#{Date.today.strftime('%d-%m-%Y')}",:class=>"form-control"
  .row
    .field.col-xs-6
      = f.label :supplier
      = f.select :supplier_id,Supplier.all.order(:name).map{|p|[p.name,p.id]},{:include_blank =>'Select A supplier',:selected => f.object.supplier_id},:class=>'chzn-select form-control',onchange: 'find_supplier(this)'
  .row
    .field.col-xs-6
      = label_tag :billing_address
      = text_area_tag :billing_address,if f.object.supplier.nil? then '' else f.object.supplier.address  end ,:class=>"form-control"
  .field
  .field{:style=>'display:inline-block;'}
    =f.label :bill_item
  .field{:style=>'display:inline-block;padding-left:124px;'}
    =f.label :account
  .field{:style=>'display:inline-block;padding-left:123px;'}
    =f.label :qty
  .field{:style=>'display:inline-block;padding-left:35px;'}
    =f.label :price
  .field{:style=>'display:inline-block;padding-left:35px;'}
    =f.label :amount
  .field{:style=>'display:inline-block;padding-left:35px;'}
    =f.label "Tax(included)"  
  .field
    = f.fields_for :bill_items do |bill_item|
      = render "bill_items_fields", :f => bill_item
    %p= link_to_add_fields "Add more", f,:bill_items
  .field{:style=>'margin-left:465px;'}
    = f.text_field :amount,:placeholder=>'0.0',:value=>f.object.amount,:style=>'width:80px;',:id=>"bill_amount",:class=>"form-control"
  .field
    = f.label :internal_information
    = f.text_area :internal_information,:class=>"form-control"
  %br
  .actions
    = f.submit 'Create',:class=>'btn btn-primary'
    = link_to 'Back', bills_path,:class=>'btn btn-default'

app/views/bills/edit.html.haml
.row
  .col-md-12.content-wrapper
    %h3 Editing Bill
    %hr
    = render 'form'

app/views/bills/index.html.haml
.row
  .pull-right
    = form_for bills_path,:method=>'GET',:html=>{:class=>'navbar-form navbar-left'} do
      = text_field_tag :search,params[:search],:placeholder=>'Search...',:style=>'width:290px;',:class=>"form-control"
.row
  .col-md-12.content-wrapper
    .row
      .col-md-12
        %table.table.table-condensed.table-striped.table-bordered.table-responsive{:id=>'sortable'}
          %tr
            %th{:colspan=>9}
              %h4{:style=>"display:inline; padding-right: 20px; line-height: 1.5em"}
                Bills
              = link_to 'New Bill', new_bill_path,:class=>"btn btn-default pull-right"
          %tr.table-header-row.table-striped
            %th
              %i.icon-edit
            %th
              %i.icon-eye-open
            %th=sortable "issue_date"
            %th #
            %th Supplier
            %th.amount=sortable "amount" 
            %th.amount Balance Due 
            %th DueDate
          - @bills.each do |bill|
            %tr
              - if bill.transactions.count > 0
                %td=image_tag "lock.jpeg",:height=>'20px',:width=>'30px',:class=>'btn btn-default btn-xs'
              -else
                %td= link_to 'Edit', edit_bill_path(bill),:class=>"btn btn-default btn-xs active"            
              %td= link_to 'View', bill,:class=>"btn btn-default btn-xs active"
              %td= bill.issue_date.strftime('%d/%m/%Y') if !bill.issue_date.nil?
              %td= bill.reference_no if !bill.reference_no.nil?
              %td= bill.supplier.name if !bill.supplier.nil?
              %th.amount= number_to_currency(bill.amount,unit:'') if !bill.amount.nil?            
              %th.amount= number_to_currency(bill.amount.to_f - bill.amount_paid.to_f,unit:'') if !bill.amount.nil?
              %td= bill.due_date.strftime('%d/%m/%Y')  if !bill.due_date.nil?  
  = will_paginate @bills,:renderer => BootstrapPagination::Rails                      

app/views/bills/new.html.haml
.row
  .col-md-12.content-wrapper
    %h3 Create Bill
    %hr
    = render 'form'

app/views/bills/show.html.haml
.row
  .col-md-12.content-wrapper
    .row  
      .col-md-12
        .col-md-3.pull-right
          %b Reference no:
          = @bill.reference_no   
        .col-md-6
          %h2 Purchase Invoice
          %br
          %br
    .row
      .col-md-6
        %p
          %b From:
          = @bill.supplier.name
        %p
          %b 
          = @bill.supplier.address
      .col-md-4.pull-right
        %p
          %b Date:
          = @bill.issue_date.strftime('%d/%m/%Y')
        %p
          %b Due Date:
          = @bill.due_date.strftime('%d/%m/%Y')
    %br
    %table.table.table-bordered.table-responsive
      %tr.table-header-row.table-striped
        %th Item & Specification
        %th.amount Qty
        %th.amount Price
        %th.amount Amount

      - @bill.bill_items.each do |bill_item|
        %tr
          %td.borderless= bill_item.item.name
          %td.amount= bill_item.qty
          %td.amount= number_to_currency(bill_item.price.round(2), unit:'')
          %td.amount= number_to_currency(bill_item.amount.round(2),unit:'')
      %tr
        %th.borderless.amount{:colspan=>3}Total
        %th.amount= number_to_currency(@bill.amount,unit:'')
      - @bill.bill_items.group('tax_code_id').select('SUM(tax_amount) as tax_amount,tax_code_id').each do |tax|
        -if !tax.tax_code.blank?
          %tr
            %td.borderless.amount{:colspan=>3}=tax.tax_code.name+"  #{tax.tax_code.rate}%"+" "+"(Included)"
            %td.amount= number_to_currency(tax.tax_amount,unit:'')
      %tr
        %td.borderless.amount{:colspan=>3}Amount Paid
        %td.amount= if @bill.amount_paid.blank? then '0.00' else number_to_currency(@bill.amount_paid,unit:'') end
      %tr
        %th.amount{:colspan=>3}Balance Due
        %th.amount= number_to_currency(@bill.amount.to_f - @bill.amount_paid.to_f,unit:'')
    %br
    .col-md-12
      %p
        %b **Additional Note:
        =@bill.internal_information
%br
  - if @bill.transactions.count > 0
    %table.table.table-bordered.table-responsive
      %tr
        %th{:colspan=>6}
          %h4{:style=>"display:inline; padding-right: 20px; line-height: 1.5em"}
            Bill Payments
          = link_to 'Pay money to Supplier', new_bill_payment_voucher_path(:bill_id=>@bill.id),:class=>'btn btn-primary pull-right'
      %tr.table-header-row.table-striped
        %th
          %i.icon-edit
        %th #
        %th Date
        %th Description
        %th Received in
        %th.amount Amount
      -if @bill.bill_payments.count >0
        - @bill.bill_payments.each do |bill_payment|
          %tr.table-header-row.table-striped
            %td=link_to 'Edit', edit_bill_payment_voucher_path(bill_payment,:bill_id=>@bill),:class=>"btn btn-default btn-xs active"
            %th= bill_payment.bill_payment_voucher.reference_no
            %td= bill_payment.bill_payment_voucher.payment_date
            %td= bill_payment.bill_payment_voucher.description
            %td= bill_payment.bill_payment_voucher.account.name
            %td.amount= number_to_currency(bill_payment.amount.round(2),unit:'')
      - else
        %tr
          %th{:colspan=>6} No Payment to supplier for this Bill

%br
  - if @bill.transactions.count <= 0
    = link_to 'Edit this Bill', edit_bill_path(@bill),:class=>'btn btn-default'
    = link_to 'Save this Bill', transaction_bill_path(@bill),:class=>'btn btn-primary',data: { disable_with: "Please wait..." }