config/routes.rb
Account::Application.routes.draw do

  resources :productions,:except=>[:destroy] do
    member do
      get :approved
    end
  end

  resources :summaries,:only=>[:index,:edit,:update]

  resources :bill_return_vouchers,:except=>[:destroy]

  resources :invoice_return_vouchers,:except=>[:destroy]

  resources :balance_sheets,:except=>[:destroy]

  resources :profit_and_losses,:except=>[:destroy]

  resources :general_ledgers,:except=>[:destroy]

  resources :trial_balances,:except=>[:destroy]
  resources :general_receipt_vouchers,:except=>[:destroy,:show]

  resources :invoice_receipt_vouchers,:except=>[:destroy,:index,:show]

  resources :general_payment_vouchers,:except=>[:destroy,:show]

  resources :bill_payment_vouchers,:except=>[:destroy,:index,:show]

  resources :journal_vouchers,:except=>[:destroy,:show] 

  resources :bills,:except=>[:destroy] do
  member do
    get :transaction
  end
  end

  resources :invoice_items,:except=>[:destroy]

  resources :invoices,:except=>[:destroy] do
    member do
      get :transaction
    end
  end
  resources :return_invoices,:except=>[:index,:destroy] do
  member do
    get :transaction
  end
  end
  resources :customers,:except=>[:destroy]

  resources :suppliers,:except=>[:destroy]

  resources :tax_codes,:except=>[:show,:destroy]

  resources :items,:except=>[:show,:destroy]

  resources :accounts,:except=>[:destroy]

  get "find_customer/:id" => "customers#find_customer"
  get "find_supplier/:id" => "suppliers#find_supplier"
  get 'payment' => "payment_vouchers#index"
  get 'report'  => "reports#index"
  get "settings" =>"settings#index"
  get "inventory" =>"inventory#index"
  root 'summaries#index'

  

end

app/controllers/profit_and_losses_controller.rb
class ProfitAndLossesController < ApplicationController
  before_action :set_profit_and_loss, only: [:show, :edit, :update, :destroy]

  # GET /profit_and_losses
  # GET /profit_and_losses.json
  def index
    @profit_and_losses = ProfitAndLoss.all
  end

  # GET /profit_and_losses/1
  # GET /profit_and_losses/1.json
  def show
    income_account = Plutus::Account.where(:type=>'Plutus::Revenue').map {|t| t.id}.join(', ')
    expense_account = Plutus::Account.where(:type=>'Plutus::Expense').map {|t| t.id}.join(', ')
    @period_transactions = Plutus::Transaction.where('transaction_date >= ?', @profit_and_loss.from).where('transaction_date <= ?', @profit_and_loss.to).select(:id)
    transaction_id_string = @period_transactions.map {|t| t.id}.join(', ')
    @income_period_amounts = Plutus::Amount.where("account_id IN (#{income_account})").where("transaction_id IN (#{transaction_id_string})").group(:account_id)
    @expense_period_amounts = Plutus::Amount.where("account_id IN (#{expense_account})").where("transaction_id IN (#{transaction_id_string})").group(:account_id)
  end

  # GET /profit_and_losses/new
  def new
    @profit_and_loss = ProfitAndLoss.new
  end

  # GET /profit_and_losses/1/edit
  def edit
  end

  # POST /profit_and_losses
  # POST /profit_and_losses.json
  def create
    @profit_and_loss = ProfitAndLoss.new(profit_and_loss_params)

    respond_to do |format|
      if @profit_and_loss.save
        format.html { redirect_to @profit_and_loss }
        format.json { render action: 'show', status: :created, location: @profit_and_loss }
      else
        format.html { render action: 'new' }
        format.json { render json: @profit_and_loss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profit_and_losses/1
  # PATCH/PUT /profit_and_losses/1.json
  def update
    respond_to do |format|
      if @profit_and_loss.update(profit_and_loss_params)
        format.html { redirect_to @profit_and_loss}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profit_and_loss.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profit_and_loss
      @profit_and_loss = ProfitAndLoss.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profit_and_loss_params
      params.require(:profit_and_loss).permit(:from, :to)
    end
end

app/helpers/profit_and_losses_helper.rb
module ProfitAndLossesHelper
	def pl_income_balance(account,pl)
	  debit_amount  = account.debit_transactions.where('transaction_date >= ?', pl.from).where('transaction_date <= ?', pl.to).sum('amount')
	  credit_amount = account.credit_transactions.where('transaction_date >= ?', pl.from).where('transaction_date <= ?', pl.to).sum('amount')
	  return number_to_currency((credit_amount-debit_amount).round(2),unit:'',negative_format: "(%u%n)")
	end
	def pl_expense_balance(account,pl)
		debit_amount  = account.debit_transactions.where('transaction_date >= ?', pl.from).where('transaction_date <= ?', pl.to).sum('amount')
	    credit_amount = account.credit_transactions.where('transaction_date >= ?', pl.from).where('transaction_date <= ?', pl.to).sum('amount')
	    return number_to_currency((debit_amount-credit_amount).round(2),unit:'',negative_format: "(%u%n)")
	end
	def revenue(pl)
	  revenue_accounts = Plutus::Revenue.all.map {|t| t.id}.join(', ')
	  period_transactions = Plutus::Transaction.where('transaction_date >= ?', pl.from).where('transaction_date <= ?', pl.to).select(:id)
	  transaction_id_string = period_transactions.map {|t| t.id}.join(', ')
      period_amounts = Plutus::Amount.where("account_id IN (#{revenue_accounts})").where("transaction_id IN (#{transaction_id_string})")
	  balance = BigDecimal.new('0')
		period_amounts.each do |amount_record|
		  if amount_record.type == "Plutus::DebitAmount"
		    balance -= amount_record.amount
		  else
		    balance += amount_record.amount
		  end
		end
        return balance
	end
	def expense(pl)
	  expense_accounts = Plutus::Expense.all.map{|t| t.id}.join(', ')
	  period_transactions = Plutus::Transaction.where('transaction_date >= ?', pl.from).where('transaction_date <= ?', pl.to).select(:id)
	  transaction_id_string = period_transactions.map {|t| t.id}.join(', ')
      period_amounts = Plutus::Amount.where("account_id IN (#{expense_accounts})").where("transaction_id IN (#{transaction_id_string})")
	  balance = BigDecimal.new('0')
		period_amounts.each do |amount_record|
		  if amount_record.type == "Plutus::DebitAmount"
		    balance += amount_record.amount
		  else
		    balance -= amount_record.amount
		  end
		end
        return balance
	end

	def pl_closing_stock(upto)
	  inventory_in = InventoryIn.joins(:item).where("in_date <= ?",upto).where("items.item_type= ?",'ca').sum(:amount)
	  inventory_out = InventoryOut.joins(:item).where("out_date <= ?",upto).where("items.item_type= ?",'ca').sum(:amount)
	  closing_stock = inventory_in - inventory_out
	  return closing_stock.round(2)
    end
	def pl_opening_stock(upto)
      inventory_in = InventoryIn.joins(:item).where("in_date < ?",upto).where("items.item_type= ?",'ca').sum(:amount)
	  inventory_out = InventoryOut.joins(:item).where("out_date < ?",upto).where("items.item_type= ?",'ca').sum(:amount)
	  opening_stock =  inventory_in - inventory_out
	  return opening_stock.round(2)
    end
	def pl_cost_of_goods_sold(from,to)
	  cost_of_goods_sold = InventoryOut.joins(:item).where("out_date >= ?",from).where("out_date <= ?",to).where("items.item_type= ?",'ca').sum(:amount)
	  return cost_of_goods_sold.round(2)
     
    end
	def profit_loss_statement(pl)
	  profit_or_loss = ((revenue(pl)+pl_closing_stock(pl.to))-(expense(pl)+pl_opening_stock(pl.from)))
	  return number_to_currency(profit_or_loss.round(2),unit:'',negative_format: "(%u%n)")
	end
end

 

app/views/profit_and_losses/_form.html.haml
= form_for @profit_and_loss do |f|
  - if @profit_and_loss.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profit_and_loss.errors.count, "error")} prohibited this profit_and_loss from being saved:"
      %ul
        - @profit_and_loss.errors.full_messages.each do |msg|
          %li= msg
  .row
    .field.col-xs-3
      = f.label :from
      = f.text_field :from,'data-behaviour' => 'datepicker',value: "#{Date.today.strftime('%d-%m-%Y')}",:class=>"form-control"
    .field.col-xs-3
      = f.label :to
      = f.text_field :to,'data-behaviour' => 'datepicker',value: "#{Date.today.strftime('%d-%m-%Y')}",:class=>"form-control"
  %br
  .actions
    = f.submit 'Save',:class=>'btn btn-primary'
    = link_to 'Back', profit_and_losses_path,:class=>'btn btn-default'

app/views/profit_and_losses/edit.html.haml
.row
  .col-md-12.content-wrapper
    %h3 Profit and Loss Statement
    %hr
    = render 'form'

app/views/profit_and_losses/index.html.haml
.row
  .col-md-12.content-wrapper
    .row
      .col-md-12
        %table.table.table-condensed.table-striped.table-bordered.table-responsive
          %tr
            %th{:colspan=>5}
              %h4{:style=>"display:inline; padding-right: 20px; line-height: 1.5em"}
                Profit and Loss Statement
              = link_to 'New Profit & Loss statement', new_profit_and_loss_path,:class=>"btn btn-default pull-right"
          %tr.table-header-row.table-striped
            %th{:style=>'width:15px;'}
              %i.icon-edit
            %th{:style=>'width:15px;'}
              %i.icon-eye-open             
            %th{:style=>'width:25px;'} From
            %th{:style=>'width:25px;'} To
            %th
          - @profit_and_losses.each do |profit_and_loss|
            %tr
              %td= link_to 'Edit',edit_profit_and_loss_path(profit_and_loss),:class=>"btn btn-default btn-xs active" 
              %td= link_to 'View', profit_and_loss,:class=>"btn btn-default btn-xs active"          
              %td= profit_and_loss.from.strftime('%d/%m/%Y')
              %td= profit_and_loss.to.strftime('%d/%m/%Y')
              %td

app/views/profit_and_losses/new.html.haml
.row
  .col-md-12.content-wrapper
    %h3 Profit and Loss Statement
    %hr
    = render 'form'

app/views/profit_and_losses/show.html.haml
%center
  %h4 Profit and Loss Statement
  %p
    %b For the Period From:
    = @profit_and_loss.from.strftime("%d-%m-%Y")
    %b To:
    = @profit_and_loss.to.strftime("%d-%m-%Y")
.row
  .col-md-12.content-wrapper
    %table.table.table-striped
      %tr
        %th Account Title
        %th{:class=>'amount'} Amount (Rs)
      - #income
      - if @income_period_amounts.length > 0
        %tr
          %th{:colspan=>3} Income
        - @income_period_amounts.each do |income_account|
          %tr
            %td= income_account.account.name
            %td{:class=>'amount'}= pl_income_balance(income_account.account,@profit_and_loss)
      %tr
        %td Add: Closing Stock
        %td{:class=>'amount'}= number_to_currency(pl_closing_stock(@profit_and_loss.to),unit:'',negative_format: "(%u%n)")    
      - #Expense
      - if @expense_period_amounts.length > 0
        %tr
          %th{:colspan=>3} Expenses
        - @expense_period_amounts.each do |expense_account|
          %tr
            %td= expense_account.account.name
            %td{:class=>'amount'}= pl_expense_balance(expense_account.account,@profit_and_loss)  
      %tr
        %td Add: Opening Stock
        %td{:class=>'amount'}= number_to_currency(pl_opening_stock(@profit_and_loss.from) ,unit:'',negative_format: "(%u%n)")             
      %tr
        %th Net Profit(Loss)
        %th{:class=>'amount'}= profit_loss_statement(@profit_and_loss)