config/routes.rb
Account::Application.routes.draw do

  resources :productions,:except=>[:destroy] do
    member do
      get :approved
    end
  end

  resources :summaries,:only=>[:index,:edit,:update]

  resources :bill_return_vouchers,:except=>[:destroy]

  resources :invoice_return_vouchers,:except=>[:destroy]

  resources :balance_sheets,:except=>[:destroy]

  resources :profit_and_losses,:except=>[:destroy]

  resources :general_ledgers,:except=>[:destroy]

  resources :trial_balances,:except=>[:destroy]
  resources :general_receipt_vouchers,:except=>[:destroy,:show]

  resources :invoice_receipt_vouchers,:except=>[:destroy,:index,:show]

  resources :general_payment_vouchers,:except=>[:destroy,:show]

  resources :bill_payment_vouchers,:except=>[:destroy,:index,:show]

  resources :journal_vouchers,:except=>[:destroy,:show] 

  resources :bills,:except=>[:destroy] do
  member do
    get :transaction
  end
  end

  resources :invoice_items,:except=>[:destroy]

  resources :invoices,:except=>[:destroy] do
    member do
      get :transaction
    end
  end
  resources :return_invoices,:except=>[:index,:destroy] do
  member do
    get :transaction
  end
  end
  resources :customers,:except=>[:destroy]

  resources :suppliers,:except=>[:destroy]

  resources :tax_codes,:except=>[:show,:destroy]

  resources :items,:except=>[:show,:destroy]

  resources :accounts,:except=>[:destroy]

  get "find_customer/:id" => "customers#find_customer"
  get "find_supplier/:id" => "suppliers#find_supplier"
  get 'payment' => "payment_vouchers#index"
  get 'report'  => "reports#index"
  get "settings" =>"settings#index"
  get "inventory" =>"inventory#index"
  root 'summaries#index'

  

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.haml
%center
	%h3 Report
.row
	.col-md-12.content-wrapper
		.row
			.col-md-12
				.col-md-4.report-box.btn-default{:style=>'padding-right:5px;'}
					%a{:href=>"#{customers_path}"}
						.center
							%b Customers Statements
							%p View Customers invoice details of each customers and due balance
				.col-md-4.report-box.btn-default
					%a{:href=>"#{suppliers_path}"}
						.center
							%b Suppliers Statements
							%p View Suppliers Bill details of each suppliers and due balance
				.col-md-4.report-box.btn-default
					%a{:href=>"#{general_ledgers_path}"}
						.center
							%b General Ledger
							%p View Ledger Content total debits,total credits and closing balance. 
		%br
		%br
		.row
			.col-md-12
				.col-md-4.report-box.btn-default
					%a{:href=>"#{trial_balances_path}"}
						.center
							%b Trial Balance
							%p View balance of ledger accounts in to debit and credit columns.
				.col-md-4.report-box.btn-default
					%a{:href=>"#{profit_and_losses_path}"}
						.center
							%b Profit & Loss Statement
							%p Review business performance,sales,profit margins expenses.
				.col-md-4.report-box.btn-default
					%a{:href=>"#{balance_sheets_path}"}
						.center
							%b Balance Sheet
							%p Analyse business financial strength,liquidity,solvency, and net worth. 